default:
  # 服务监听端口
  listen: 8090
  # 日志类型，支持 stdout, stderr 和 file, 默认为 stdout
  log_type: stdout
  # 日志级别，支持 INFO, WARN 和 ERROR, 默认为 INFO
  log_level: INFO
  # 日志路径，在日志类型为 file 的时候生效
  log_dir: /var/log/pixiu
  # jwt 签名的 key
  jwt_key: gopixiu

# 数据库地址信息
mysql:
  host: gopixiu
  user: root
  password: GoPixiu868686
  port: 3306
  name: gopixiu

cicd:
  driver: jenkins
  jenkins:
    host: http://8.140.165.201:9090
    user: adminops
    password: adminops@321
