default:
  # 运行模式，可选 debug 和 release
  mode: release
  # 服务监听端口
  listen: 8090
  # jwt 签名的 key
  jwt_key: pixiu
  # 自动创建指定模型的数据库表结构，不会更新已存在的数据库表
  auto_migrate: true

  log_format: json

# 数据库地址信息
mysql:
  host: peng
  user: root
  password: Pixiu868686
  port: 3306
  name: pixiu
